### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by e-p-s** [DominikPieper/obsidian-ReadItLater#129]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

With some videos I get "Video not available
Watch on YouTube" in the iframe.

e.g.

Video nicht verfügbar
[Auf YouTube ansehen](http://www.youtube.com/watch?v=_IJ-Dqm9E-8)

# [Adele - Someone Like You (Official Music Video)](https://www.youtube.com/watch?v=hLQl3WQQoQ0)

### Current behaviour

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/42796829/bec3aebd-0ce2-4285-957a-a1240bb4b083)

### Steps to reproduce

copy youtube url in clip and hit the paste buttom in obsidian

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/42796829/e94496c4-414c-4bb1-8a41-570ed1622781)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.4.16

### Plugin Version

0.3.1

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

**Comment by adamluckdev** [comment]
Apparently, Youtube forbids embedding of some videos. I found two possible reasons:
- [Video has copyright music in background](https://help.myfitapp.de/en/articles/5450810-youtube-videos-showing-video-unavailable)
- [Localhost restrcitions](https://stackoverflow.com/a/59640711), but this seems unlikely because other videos, such as https://www.youtube.com/watch?v=U8Oj0psMaCs , embedded correctly
